version: "4.0"

services:
  node:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORTS=3000
      - MONGO_URL=${MONGO_URL}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - REDIS_URL=${REDIS_URL}
      - REDIS_PORT=${REDIS_PORT}
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: srivastav
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    volumes:
      - mongo-volumes:/data/db
  # redis:
  #   image: redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data

volumes:
  mongo-volumes:
  # redis-data:
